/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import ahorcado.Juego;
import javax.swing.JOptionPane;
import modelo.Palabras;

/**
 *
 * @author wceba
 */
public class Principal extends javax.swing.JFrame {

    public String palabra;
    public String letra;
    
    Juego juego = new Juego();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        //Cabeza(Boolean.FALSE);
        initComponents();
        palabra = juego.MostrarPalabra();
        lblPalabraOculta.setText(palabra);


    }

    public Boolean Cabeza(Boolean valor){
        Boolean mostrar = valor;
        return mostrar;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblTituloJuego = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblPalabraAAdivinar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLetra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblListaLetras = new javax.swing.JLabel();
        lblPalabraOculta = new javax.swing.JLabel();
        lblImagen1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego del Ahorcado");

        lblTituloJuego.setText("Juego del Ahorcado");

        jLabel1.setText("Adivine la Palabra:");

        lblPalabraAAdivinar.setText("_ _ _ _ _ _");

        jLabel3.setText("Ingrese una Letra:");

        txtLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLetraActionPerformed(evt);
            }
        });

        jLabel4.setText("Lista de letras ingresadas:");

        lblListaLetras.setText("Mostrar las letras");

        lblImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1.png"))); // NOI18N
        lblImagen1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPalabraAAdivinar)
                                .addGap(88, 88, 88)
                                .addComponent(lblPalabraOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(lblTituloJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblListaLetras)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTituloJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPalabraAAdivinar)
                            .addComponent(lblPalabraOculta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(lblListaLetras)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        setBounds(250, 100, 516, 351);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLetraActionPerformed
        letra = txtLetra.getText();
        Palabras PalabraArmada = new Palabras();
        PalabraArmada.GuardarLetra(letra);
        jLabel5.setText(palabra+'-'+letra);
        System.out.println("letra: "+letra);
        System.out.println("esta: "+juego.BuscarLetra(palabra, letra));
        System.out.println("guardando letras: "+PalabraArmada.ArmarPalabra(PalabraArmada.GuardarLetra(letra)));
        
        lblListaLetras.setText("Letra ingresada "+txtLetra.getText());
        
        Boolean esta = null;
        
        for (int i = 0; i < palabra.length(); i++) {
            String pa = palabra.substring(i, i);
            
            if (!pa.equals(letra)){
                System.out.println("false palabra y letra"+palabra+"-"+letra);
                esta = Boolean.FALSE;
            }else{
                System.out.println("true palabra y letra"+palabra+"-"+letra);
                esta = Boolean.TRUE;
            }
        }        
        
        txtLetra.setText("");
        
//        JOptionPane jp = new JOptionPane();
//        jp.showMessageDialog(null, juego.BuscarLetra(palabra, letra));
    }//GEN-LAST:event_txtLetraActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblImagen1;
    private javax.swing.JLabel lblListaLetras;
    private javax.swing.JLabel lblPalabraAAdivinar;
    private javax.swing.JLabel lblPalabraOculta;
    private javax.swing.JLabel lblTituloJuego;
    private javax.swing.JTextField txtLetra;
    // End of variables declaration//GEN-END:variables
}
