/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado.Vista;

/**
 *
 * @author TheGuru
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonC = new javax.swing.JToggleButton();
        botonA = new javax.swing.JToggleButton();
        botonB = new javax.swing.JToggleButton();
        botonD = new javax.swing.JToggleButton();
        botonE = new javax.swing.JToggleButton();
        botonF = new javax.swing.JToggleButton();
        botonI = new javax.swing.JToggleButton();
        botonG = new javax.swing.JToggleButton();
        botonH = new javax.swing.JToggleButton();
        botonJ = new javax.swing.JToggleButton();
        botonK = new javax.swing.JToggleButton();
        botonL = new javax.swing.JToggleButton();
        botonÑ = new javax.swing.JToggleButton();
        botonM = new javax.swing.JToggleButton();
        botonN = new javax.swing.JToggleButton();
        botonO = new javax.swing.JToggleButton();
        botonP = new javax.swing.JToggleButton();
        botonQ = new javax.swing.JToggleButton();
        botonT = new javax.swing.JToggleButton();
        R = new javax.swing.JToggleButton();
        botonS = new javax.swing.JToggleButton();
        botonU = new javax.swing.JToggleButton();
        botonV = new javax.swing.JToggleButton();
        botonW = new javax.swing.JToggleButton();
        botonZ = new javax.swing.JToggleButton();
        botonX = new javax.swing.JToggleButton();
        botonY = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabLetrasBotones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonC.setText("C");
        botonC.setMaximumSize(new java.awt.Dimension(45, 25));
        botonC.setMinimumSize(new java.awt.Dimension(45, 25));
        botonC.setPreferredSize(new java.awt.Dimension(45, 25));
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        getContentPane().add(botonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 45, 25));

        botonA.setText("A");
        botonA.setMaximumSize(new java.awt.Dimension(45, 25));
        botonA.setMinimumSize(new java.awt.Dimension(45, 25));
        botonA.setPreferredSize(new java.awt.Dimension(45, 25));
        botonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAActionPerformed(evt);
            }
        });
        getContentPane().add(botonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 45, 25));

        botonB.setText("B");
        botonB.setMaximumSize(new java.awt.Dimension(45, 25));
        botonB.setMinimumSize(new java.awt.Dimension(45, 25));
        botonB.setPreferredSize(new java.awt.Dimension(45, 25));
        botonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBActionPerformed(evt);
            }
        });
        getContentPane().add(botonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 45, 25));

        botonD.setText("D");
        botonD.setMaximumSize(new java.awt.Dimension(45, 25));
        botonD.setMinimumSize(new java.awt.Dimension(45, 25));
        botonD.setPreferredSize(new java.awt.Dimension(45, 25));
        botonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDActionPerformed(evt);
            }
        });
        getContentPane().add(botonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 45, 25));

        botonE.setText("E");
        botonE.setMaximumSize(new java.awt.Dimension(45, 25));
        botonE.setMinimumSize(new java.awt.Dimension(45, 25));
        botonE.setPreferredSize(new java.awt.Dimension(45, 25));
        botonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEActionPerformed(evt);
            }
        });
        getContentPane().add(botonE, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 45, 25));

        botonF.setText("F");
        botonF.setMaximumSize(new java.awt.Dimension(45, 25));
        botonF.setMinimumSize(new java.awt.Dimension(45, 25));
        botonF.setPreferredSize(new java.awt.Dimension(45, 25));
        botonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFActionPerformed(evt);
            }
        });
        getContentPane().add(botonF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 45, 25));

        botonI.setText("I");
        botonI.setMaximumSize(new java.awt.Dimension(45, 25));
        botonI.setMinimumSize(new java.awt.Dimension(45, 25));
        botonI.setPreferredSize(new java.awt.Dimension(45, 25));
        botonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIActionPerformed(evt);
            }
        });
        getContentPane().add(botonI, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 45, 25));

        botonG.setText("G");
        botonG.setMaximumSize(new java.awt.Dimension(45, 25));
        botonG.setMinimumSize(new java.awt.Dimension(45, 25));
        botonG.setPreferredSize(new java.awt.Dimension(45, 25));
        botonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGActionPerformed(evt);
            }
        });
        getContentPane().add(botonG, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 45, 25));

        botonH.setText("H");
        botonH.setMaximumSize(new java.awt.Dimension(45, 25));
        botonH.setMinimumSize(new java.awt.Dimension(45, 25));
        botonH.setPreferredSize(new java.awt.Dimension(45, 25));
        botonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHActionPerformed(evt);
            }
        });
        getContentPane().add(botonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 45, 25));

        botonJ.setText("J");
        botonJ.setMaximumSize(new java.awt.Dimension(45, 25));
        botonJ.setMinimumSize(new java.awt.Dimension(45, 25));
        botonJ.setPreferredSize(new java.awt.Dimension(45, 25));
        botonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJActionPerformed(evt);
            }
        });
        getContentPane().add(botonJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 45, 25));

        botonK.setText("K");
        botonK.setMaximumSize(new java.awt.Dimension(45, 25));
        botonK.setMinimumSize(new java.awt.Dimension(45, 25));
        botonK.setPreferredSize(new java.awt.Dimension(45, 25));
        botonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonKActionPerformed(evt);
            }
        });
        getContentPane().add(botonK, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 45, 25));

        botonL.setText("L");
        botonL.setMaximumSize(new java.awt.Dimension(45, 25));
        botonL.setMinimumSize(new java.awt.Dimension(45, 25));
        botonL.setPreferredSize(new java.awt.Dimension(45, 25));
        botonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLActionPerformed(evt);
            }
        });
        getContentPane().add(botonL, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 45, 25));

        botonÑ.setText("Ñ");
        botonÑ.setMaximumSize(new java.awt.Dimension(45, 25));
        botonÑ.setMinimumSize(new java.awt.Dimension(45, 25));
        botonÑ.setPreferredSize(new java.awt.Dimension(45, 25));
        botonÑ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonÑActionPerformed(evt);
            }
        });
        getContentPane().add(botonÑ, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 45, 25));

        botonM.setText("M");
        botonM.setMaximumSize(new java.awt.Dimension(45, 25));
        botonM.setMinimumSize(new java.awt.Dimension(45, 25));
        botonM.setPreferredSize(new java.awt.Dimension(45, 25));
        botonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMActionPerformed(evt);
            }
        });
        getContentPane().add(botonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 45, 25));

        botonN.setText("N");
        botonN.setMaximumSize(new java.awt.Dimension(45, 25));
        botonN.setMinimumSize(new java.awt.Dimension(45, 25));
        botonN.setPreferredSize(new java.awt.Dimension(45, 25));
        botonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNActionPerformed(evt);
            }
        });
        getContentPane().add(botonN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 45, 25));

        botonO.setText("O");
        botonO.setMaximumSize(new java.awt.Dimension(45, 25));
        botonO.setMinimumSize(new java.awt.Dimension(45, 25));
        botonO.setPreferredSize(new java.awt.Dimension(45, 25));
        botonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOActionPerformed(evt);
            }
        });
        getContentPane().add(botonO, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 45, 25));

        botonP.setText("P");
        botonP.setMaximumSize(new java.awt.Dimension(45, 25));
        botonP.setMinimumSize(new java.awt.Dimension(45, 25));
        botonP.setPreferredSize(new java.awt.Dimension(45, 25));
        botonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPActionPerformed(evt);
            }
        });
        getContentPane().add(botonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 45, 25));

        botonQ.setText("Q");
        botonQ.setMaximumSize(new java.awt.Dimension(45, 25));
        botonQ.setMinimumSize(new java.awt.Dimension(45, 25));
        botonQ.setPreferredSize(new java.awt.Dimension(45, 25));
        botonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQActionPerformed(evt);
            }
        });
        getContentPane().add(botonQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 45, 25));

        botonT.setText("T");
        botonT.setMaximumSize(new java.awt.Dimension(45, 25));
        botonT.setMinimumSize(new java.awt.Dimension(45, 25));
        botonT.setPreferredSize(new java.awt.Dimension(45, 25));
        botonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTActionPerformed(evt);
            }
        });
        getContentPane().add(botonT, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 45, 25));

        R.setText("R");
        R.setMaximumSize(new java.awt.Dimension(45, 25));
        R.setMinimumSize(new java.awt.Dimension(45, 25));
        R.setPreferredSize(new java.awt.Dimension(45, 25));
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });
        getContentPane().add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 45, 25));

        botonS.setText("S");
        botonS.setMaximumSize(new java.awt.Dimension(45, 25));
        botonS.setMinimumSize(new java.awt.Dimension(45, 25));
        botonS.setPreferredSize(new java.awt.Dimension(45, 25));
        botonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSActionPerformed(evt);
            }
        });
        getContentPane().add(botonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 45, 25));

        botonU.setText("U");
        botonU.setMaximumSize(new java.awt.Dimension(45, 25));
        botonU.setMinimumSize(new java.awt.Dimension(45, 25));
        botonU.setPreferredSize(new java.awt.Dimension(45, 25));
        botonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUActionPerformed(evt);
            }
        });
        getContentPane().add(botonU, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 45, 25));

        botonV.setText("V");
        botonV.setMaximumSize(new java.awt.Dimension(45, 25));
        botonV.setMinimumSize(new java.awt.Dimension(45, 25));
        botonV.setPreferredSize(new java.awt.Dimension(45, 25));
        botonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVActionPerformed(evt);
            }
        });
        getContentPane().add(botonV, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 45, 25));

        botonW.setText("W");
        botonW.setMaximumSize(new java.awt.Dimension(45, 25));
        botonW.setMinimumSize(new java.awt.Dimension(45, 25));
        botonW.setPreferredSize(new java.awt.Dimension(45, 25));
        botonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonWActionPerformed(evt);
            }
        });
        getContentPane().add(botonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 45, 25));

        botonZ.setText("Z");
        botonZ.setMaximumSize(new java.awt.Dimension(45, 25));
        botonZ.setMinimumSize(new java.awt.Dimension(45, 25));
        botonZ.setPreferredSize(new java.awt.Dimension(45, 25));
        botonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonZActionPerformed(evt);
            }
        });
        getContentPane().add(botonZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 45, 25));

        botonX.setText("X");
        botonX.setMaximumSize(new java.awt.Dimension(45, 25));
        botonX.setMinimumSize(new java.awt.Dimension(45, 25));
        botonX.setPreferredSize(new java.awt.Dimension(45, 25));
        botonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonXActionPerformed(evt);
            }
        });
        getContentPane().add(botonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 45, 25));

        botonY.setText("Y");
        botonY.setMaximumSize(new java.awt.Dimension(45, 25));
        botonY.setMinimumSize(new java.awt.Dimension(45, 25));
        botonY.setPreferredSize(new java.awt.Dimension(45, 25));
        botonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonYActionPerformed(evt);
            }
        });
        getContentPane().add(botonY, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 45, 25));

        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 130, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Palabras Acertadas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, -1));

        jLabLetrasBotones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabLetrasBotones.setText("Letras Disponibles");
        getContentPane().add(jLabLetrasBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 330, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCActionPerformed

    private void botonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAActionPerformed
      botonA.setVisible(false);
    }//GEN-LAST:event_botonAActionPerformed

    private void botonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBActionPerformed
      botonB.setVisible(false);
    }//GEN-LAST:event_botonBActionPerformed

    private void botonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDActionPerformed
      botonD.setVisible(false);
    }//GEN-LAST:event_botonDActionPerformed

    private void botonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEActionPerformed
     botonE.setVisible(false);
    }//GEN-LAST:event_botonEActionPerformed

    private void botonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFActionPerformed

    private void botonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIActionPerformed

    private void botonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGActionPerformed

    private void botonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonHActionPerformed

    private void botonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonJActionPerformed

    private void botonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonKActionPerformed

    private void botonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLActionPerformed

    private void botonÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonÑActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonÑActionPerformed

    private void botonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMActionPerformed

    private void botonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonNActionPerformed

    private void botonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonOActionPerformed

    private void botonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPActionPerformed

    private void botonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonQActionPerformed

    private void botonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonTActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RActionPerformed

    private void botonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSActionPerformed

    private void botonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonUActionPerformed

    private void botonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVActionPerformed

    private void botonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonWActionPerformed

    private void botonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonZActionPerformed

    private void botonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonXActionPerformed

    private void botonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonYActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton R;
    private javax.swing.JToggleButton botonA;
    private javax.swing.JToggleButton botonB;
    private javax.swing.JToggleButton botonC;
    private javax.swing.JToggleButton botonD;
    private javax.swing.JToggleButton botonE;
    private javax.swing.JToggleButton botonF;
    private javax.swing.JToggleButton botonG;
    private javax.swing.JToggleButton botonH;
    private javax.swing.JToggleButton botonI;
    private javax.swing.JToggleButton botonJ;
    private javax.swing.JToggleButton botonK;
    private javax.swing.JToggleButton botonL;
    private javax.swing.JToggleButton botonM;
    private javax.swing.JToggleButton botonN;
    private javax.swing.JToggleButton botonO;
    private javax.swing.JToggleButton botonP;
    private javax.swing.JToggleButton botonQ;
    private javax.swing.JToggleButton botonS;
    private javax.swing.JToggleButton botonT;
    private javax.swing.JToggleButton botonU;
    private javax.swing.JToggleButton botonV;
    private javax.swing.JToggleButton botonW;
    private javax.swing.JToggleButton botonX;
    private javax.swing.JToggleButton botonY;
    private javax.swing.JToggleButton botonZ;
    private javax.swing.JToggleButton botonÑ;
    private javax.swing.JLabel jLabLetrasBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
