/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado.Vista;

import ahorcado.Controlador.PalabraControlador;
import java.util.Arrays;

/**
 *
 * @author TheGuru
 */
public class Vista extends javax.swing.JFrame {

    private int juego = 1; //Variable que indica la cantidad de partes del grafico
    private String[] palabraejemplo = {"P","A","L","A","B","R","A"};
    PalabraControlador palabraControlador;
    public Vista() {
        initComponents();
        inicioJuego();
        guiones(palabraejemplo);
        palabraControlador = new PalabraControlador();
        
    }
    
    //Metodo para Inicializar los parametros del juego
    public void inicioJuego(){
        juego=1;
        img1.setVisible(true);
        img2.setVisible(false);
        img3.setVisible(false);
        img4.setVisible(false);
        img5.setVisible(false);
        img6.setVisible(false);
        img7.setVisible(false);
        
        Jperdiste.setVisible(false);
        resetearletras();
        jLabel8.setText(String.valueOf(juego));
    }
    
    //Metodo para resetear los botones de letras
    public void resetearletras(){
        botonA.setVisible(true);
        botonB.setVisible(true);
        botonC.setVisible(true);
        botonD.setVisible(true);
        botonE.setVisible(true);
        botonF.setVisible(true);
        botonG.setVisible(true);
        botonH.setVisible(true);
        botonI.setVisible(true);
        botonJ.setVisible(true);
        botonK.setVisible(true);
        botonL.setVisible(true);
        botonM.setVisible(true);
        botonN.setVisible(true);
        botonÑ.setVisible(true);
        botonO.setVisible(true);
        botonP.setVisible(true);
        botonQ.setVisible(true);
        botonR.setVisible(true);
        botonS.setVisible(true);
        botonT.setVisible(true);
        botonU.setVisible(true);
        botonV.setVisible(true);
        botonW.setVisible(true);
        botonX.setVisible(true);
        botonY.setVisible(true);
        botonZ.setVisible(true);   
    }
    
    //Metodo para cambiar las letras de la palabra por guiones
    public void guiones (String[] palabraejemplo){
        String[] losguiones;
        losguiones = new String [palabraejemplo.length];
        for (int i = 0; i< palabraejemplo.length; i++) {
            losguiones[i]="_ ";
        }
        String guiones=Arrays.toString(losguiones).replaceAll("\\[|\\]|,|", "");
        jPalabra.setText(guiones);
    }
    
    //Metodos para probar el cambio de estado del jugador
    public void suma(){
        juego=juego+1;
        estado(juego);
        jLabel8.setText(String.valueOf(juego));
        
    }
    public void resta(){
        juego=juego-1;
        estado(juego);
        jLabel8.setText(String.valueOf(juego));
    }
    
    //Metodo que muestra como cambia la imagen del jugador
    public void estado(int juego){
        switch(juego){
            case 1:
                break;
            case 2:
                img2.setVisible(true);
                break;
            case 3:
                img3.setVisible(true);
                break;
            case 4:
                img4.setVisible(true);
                break;
            case 5:
                img5.setVisible(true);
                break;
            case 6:
                img6.setVisible(true);
                break;
            case 7:
                img7.setVisible(true);
                Jperdiste.setVisible(true);
                break;    
        }
               
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonC = new javax.swing.JButton();
        botonA = new javax.swing.JButton();
        botonB = new javax.swing.JButton();
        botonD = new javax.swing.JButton();
        botonE = new javax.swing.JButton();
        botonF = new javax.swing.JButton();
        botonI = new javax.swing.JButton();
        botonG = new javax.swing.JButton();
        botonH = new javax.swing.JButton();
        botonJ = new javax.swing.JButton();
        botonK = new javax.swing.JButton();
        botonL = new javax.swing.JButton();
        botonÑ = new javax.swing.JButton();
        botonM = new javax.swing.JButton();
        botonN = new javax.swing.JButton();
        botonO = new javax.swing.JButton();
        botonP = new javax.swing.JButton();
        botonQ = new javax.swing.JButton();
        botonT = new javax.swing.JButton();
        botonR = new javax.swing.JButton();
        botonS = new javax.swing.JButton();
        botonU = new javax.swing.JButton();
        botonV = new javax.swing.JButton();
        botonW = new javax.swing.JButton();
        botonZ = new javax.swing.JButton();
        botonX = new javax.swing.JButton();
        botonY = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabLetrasBotones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        img7 = new javax.swing.JLabel();
        jPalabra = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Jperdiste = new javax.swing.JLabel();
        jBtnSalir = new javax.swing.JButton();
        jBtnReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonC.setText("C");
        botonC.setMaximumSize(new java.awt.Dimension(45, 25));
        botonC.setMinimumSize(new java.awt.Dimension(45, 25));
        botonC.setPreferredSize(new java.awt.Dimension(45, 25));
        botonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCActionPerformed(evt);
            }
        });
        getContentPane().add(botonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 45, 25));

        botonA.setText("A");
        botonA.setMaximumSize(new java.awt.Dimension(45, 25));
        botonA.setMinimumSize(new java.awt.Dimension(45, 25));
        botonA.setPreferredSize(new java.awt.Dimension(45, 25));
        botonA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAActionPerformed(evt);
            }
        });
        getContentPane().add(botonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 45, 25));

        botonB.setText("B");
        botonB.setMaximumSize(new java.awt.Dimension(45, 25));
        botonB.setMinimumSize(new java.awt.Dimension(45, 25));
        botonB.setPreferredSize(new java.awt.Dimension(45, 25));
        botonB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBActionPerformed(evt);
            }
        });
        getContentPane().add(botonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 45, 25));

        botonD.setText("D");
        botonD.setMaximumSize(new java.awt.Dimension(45, 25));
        botonD.setMinimumSize(new java.awt.Dimension(45, 25));
        botonD.setPreferredSize(new java.awt.Dimension(45, 25));
        botonD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDActionPerformed(evt);
            }
        });
        getContentPane().add(botonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 45, 25));

        botonE.setText("E");
        botonE.setMaximumSize(new java.awt.Dimension(45, 25));
        botonE.setMinimumSize(new java.awt.Dimension(45, 25));
        botonE.setPreferredSize(new java.awt.Dimension(45, 25));
        botonE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEActionPerformed(evt);
            }
        });
        getContentPane().add(botonE, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 45, 25));

        botonF.setText("F");
        botonF.setMaximumSize(new java.awt.Dimension(45, 25));
        botonF.setMinimumSize(new java.awt.Dimension(45, 25));
        botonF.setPreferredSize(new java.awt.Dimension(45, 25));
        botonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFActionPerformed(evt);
            }
        });
        getContentPane().add(botonF, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 45, 25));

        botonI.setText("I");
        botonI.setMaximumSize(new java.awt.Dimension(45, 25));
        botonI.setMinimumSize(new java.awt.Dimension(45, 25));
        botonI.setPreferredSize(new java.awt.Dimension(45, 25));
        botonI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIActionPerformed(evt);
            }
        });
        getContentPane().add(botonI, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 45, 25));

        botonG.setText("G");
        botonG.setMaximumSize(new java.awt.Dimension(45, 25));
        botonG.setMinimumSize(new java.awt.Dimension(45, 25));
        botonG.setPreferredSize(new java.awt.Dimension(45, 25));
        botonG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGActionPerformed(evt);
            }
        });
        getContentPane().add(botonG, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 45, 25));

        botonH.setText("H");
        botonH.setMaximumSize(new java.awt.Dimension(45, 25));
        botonH.setMinimumSize(new java.awt.Dimension(45, 25));
        botonH.setPreferredSize(new java.awt.Dimension(45, 25));
        botonH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHActionPerformed(evt);
            }
        });
        getContentPane().add(botonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 45, 25));

        botonJ.setText("J");
        botonJ.setMaximumSize(new java.awt.Dimension(45, 25));
        botonJ.setMinimumSize(new java.awt.Dimension(45, 25));
        botonJ.setPreferredSize(new java.awt.Dimension(45, 25));
        botonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonJActionPerformed(evt);
            }
        });
        getContentPane().add(botonJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 45, 25));

        botonK.setText("K");
        botonK.setMaximumSize(new java.awt.Dimension(45, 25));
        botonK.setMinimumSize(new java.awt.Dimension(45, 25));
        botonK.setPreferredSize(new java.awt.Dimension(45, 25));
        botonK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonKActionPerformed(evt);
            }
        });
        getContentPane().add(botonK, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 45, 25));

        botonL.setText("L");
        botonL.setMaximumSize(new java.awt.Dimension(45, 25));
        botonL.setMinimumSize(new java.awt.Dimension(45, 25));
        botonL.setPreferredSize(new java.awt.Dimension(45, 25));
        botonL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLActionPerformed(evt);
            }
        });
        getContentPane().add(botonL, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 45, 25));

        botonÑ.setText("Ñ");
        botonÑ.setMaximumSize(new java.awt.Dimension(45, 25));
        botonÑ.setMinimumSize(new java.awt.Dimension(45, 25));
        botonÑ.setPreferredSize(new java.awt.Dimension(45, 25));
        botonÑ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonÑActionPerformed(evt);
            }
        });
        getContentPane().add(botonÑ, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 45, 25));

        botonM.setText("M");
        botonM.setMaximumSize(new java.awt.Dimension(45, 25));
        botonM.setMinimumSize(new java.awt.Dimension(45, 25));
        botonM.setPreferredSize(new java.awt.Dimension(45, 25));
        botonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMActionPerformed(evt);
            }
        });
        getContentPane().add(botonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 45, 25));

        botonN.setText("N");
        botonN.setMaximumSize(new java.awt.Dimension(45, 25));
        botonN.setMinimumSize(new java.awt.Dimension(45, 25));
        botonN.setPreferredSize(new java.awt.Dimension(45, 25));
        botonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNActionPerformed(evt);
            }
        });
        getContentPane().add(botonN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 45, 25));

        botonO.setText("O");
        botonO.setMaximumSize(new java.awt.Dimension(45, 25));
        botonO.setMinimumSize(new java.awt.Dimension(45, 25));
        botonO.setPreferredSize(new java.awt.Dimension(45, 25));
        botonO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOActionPerformed(evt);
            }
        });
        getContentPane().add(botonO, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 45, 25));

        botonP.setText("P");
        botonP.setMaximumSize(new java.awt.Dimension(45, 25));
        botonP.setMinimumSize(new java.awt.Dimension(45, 25));
        botonP.setPreferredSize(new java.awt.Dimension(45, 25));
        botonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPActionPerformed(evt);
            }
        });
        getContentPane().add(botonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 45, 25));

        botonQ.setText("Q");
        botonQ.setMaximumSize(new java.awt.Dimension(45, 25));
        botonQ.setMinimumSize(new java.awt.Dimension(45, 25));
        botonQ.setPreferredSize(new java.awt.Dimension(45, 25));
        botonQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQActionPerformed(evt);
            }
        });
        getContentPane().add(botonQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 45, 25));

        botonT.setText("T");
        botonT.setMaximumSize(new java.awt.Dimension(45, 25));
        botonT.setMinimumSize(new java.awt.Dimension(45, 25));
        botonT.setPreferredSize(new java.awt.Dimension(45, 25));
        botonT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTActionPerformed(evt);
            }
        });
        getContentPane().add(botonT, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 45, 25));

        botonR.setText("R");
        botonR.setMaximumSize(new java.awt.Dimension(45, 25));
        botonR.setMinimumSize(new java.awt.Dimension(45, 25));
        botonR.setPreferredSize(new java.awt.Dimension(45, 25));
        botonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRActionPerformed(evt);
            }
        });
        getContentPane().add(botonR, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 45, 25));

        botonS.setText("S");
        botonS.setMaximumSize(new java.awt.Dimension(45, 25));
        botonS.setMinimumSize(new java.awt.Dimension(45, 25));
        botonS.setPreferredSize(new java.awt.Dimension(45, 25));
        botonS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSActionPerformed(evt);
            }
        });
        getContentPane().add(botonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 45, 25));

        botonU.setText("U");
        botonU.setMaximumSize(new java.awt.Dimension(45, 25));
        botonU.setMinimumSize(new java.awt.Dimension(45, 25));
        botonU.setPreferredSize(new java.awt.Dimension(45, 25));
        botonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUActionPerformed(evt);
            }
        });
        getContentPane().add(botonU, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 45, 25));

        botonV.setText("V");
        botonV.setMaximumSize(new java.awt.Dimension(45, 25));
        botonV.setMinimumSize(new java.awt.Dimension(45, 25));
        botonV.setPreferredSize(new java.awt.Dimension(45, 25));
        botonV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVActionPerformed(evt);
            }
        });
        getContentPane().add(botonV, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 45, 25));

        botonW.setText("W");
        botonW.setMaximumSize(new java.awt.Dimension(45, 25));
        botonW.setMinimumSize(new java.awt.Dimension(45, 25));
        botonW.setPreferredSize(new java.awt.Dimension(45, 25));
        botonW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonWActionPerformed(evt);
            }
        });
        getContentPane().add(botonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 45, 25));

        botonZ.setText("Z");
        botonZ.setMaximumSize(new java.awt.Dimension(45, 25));
        botonZ.setMinimumSize(new java.awt.Dimension(45, 25));
        botonZ.setPreferredSize(new java.awt.Dimension(45, 25));
        botonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonZActionPerformed(evt);
            }
        });
        getContentPane().add(botonZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 45, 25));

        botonX.setText("X");
        botonX.setMaximumSize(new java.awt.Dimension(45, 25));
        botonX.setMinimumSize(new java.awt.Dimension(45, 25));
        botonX.setPreferredSize(new java.awt.Dimension(45, 25));
        botonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonXActionPerformed(evt);
            }
        });
        getContentPane().add(botonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 45, 25));

        botonY.setText("Y");
        botonY.setMaximumSize(new java.awt.Dimension(45, 25));
        botonY.setMinimumSize(new java.awt.Dimension(45, 25));
        botonY.setPreferredSize(new java.awt.Dimension(45, 25));
        botonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonYActionPerformed(evt);
            }
        });
        getContentPane().add(botonY, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 45, 25));

        jList1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 130, 190));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Palabras Acertadas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, -1, -1));

        jLabLetrasBotones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabLetrasBotones.setText("Letras Disponibles");
        getContentPane().add(jLabLetrasBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 330, 190));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Ahorcado v0.1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/Imagenes/1.png"))); // NOI18N
        getContentPane().add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 320));

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/Imagenes/2.png"))); // NOI18N
        getContentPane().add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 320));

        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/Imagenes/3.png"))); // NOI18N
        getContentPane().add(img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 320));

        img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/Imagenes/4.png"))); // NOI18N
        getContentPane().add(img4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 320));

        img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/Imagenes/5.png"))); // NOI18N
        getContentPane().add(img5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 320));

        img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/Imagenes/6.png"))); // NOI18N
        getContentPane().add(img6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 320));

        img7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ahorcado/Imagenes/7.png"))); // NOI18N
        getContentPane().add(img7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 320));

        jPalabra.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jPalabra.setText("_ _ _ _ _ _ _ _ _ _ _ _");
        getContentPane().add(jPalabra, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 370, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1000, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Puntaje:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 70, 20));

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, -1, -1));

        jLabel8.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabel8PropertyChange(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 70, 30));

        Jperdiste.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Jperdiste.setForeground(new java.awt.Color(255, 51, 51));
        Jperdiste.setText("Perdiste");
        getContentPane().add(Jperdiste, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 310, -1, -1));

        jBtnReiniciar.setText("Reiniciar");
        jBtnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCActionPerformed
      botonC.setVisible(false);
      palabraControlador.verificarLetra("C");// TODO add your handling code here:
    }//GEN-LAST:event_botonCActionPerformed

    private void botonAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAActionPerformed
      botonA.setVisible(false);
      palabraControlador.verificarLetra("A");
    }//GEN-LAST:event_botonAActionPerformed

    private void botonBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBActionPerformed
      botonB.setVisible(false);
      palabraControlador.verificarLetra("B");
    }//GEN-LAST:event_botonBActionPerformed

    private void botonDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDActionPerformed
      botonD.setVisible(false);
      palabraControlador.verificarLetra("D");
    }//GEN-LAST:event_botonDActionPerformed

    private void botonEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEActionPerformed
     botonE.setVisible(false);
     palabraControlador.verificarLetra("E");
    }//GEN-LAST:event_botonEActionPerformed

    private void botonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFActionPerformed
       botonF.setVisible(false);
       palabraControlador.verificarLetra("F");// TODO add your handling code here:
    }//GEN-LAST:event_botonFActionPerformed

    private void botonIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIActionPerformed
      botonI.setVisible(false);
      palabraControlador.verificarLetra("I");// TODO add your handling code here:
    }//GEN-LAST:event_botonIActionPerformed

    private void botonGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGActionPerformed
     botonG.setVisible(false);
     palabraControlador.verificarLetra("G");// TODO add your handling code here:
    }//GEN-LAST:event_botonGActionPerformed

    private void botonHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHActionPerformed
       botonH.setVisible(false);
       palabraControlador.verificarLetra("H");// TODO add your handling code here:
    }//GEN-LAST:event_botonHActionPerformed

    private void botonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJActionPerformed
      botonJ.setVisible(false);
      palabraControlador.verificarLetra("J");// TODO add your handling code here:
    }//GEN-LAST:event_botonJActionPerformed

    private void botonKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonKActionPerformed
      botonK.setVisible(false);
      palabraControlador.verificarLetra("K");// TODO add your handling code here:
    }//GEN-LAST:event_botonKActionPerformed

    private void botonLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLActionPerformed
      botonL.setVisible(false);
      palabraControlador.verificarLetra("L");// TODO add your handling code here:
    }//GEN-LAST:event_botonLActionPerformed

    private void botonÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonÑActionPerformed
        botonÑ.setVisible(false);
        palabraControlador.verificarLetra("Ñ");// TODO add your handling code here:
    }//GEN-LAST:event_botonÑActionPerformed

    private void botonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMActionPerformed
       botonM.setVisible(false);
       palabraControlador.verificarLetra("M");// TODO add your handling code here:
    }//GEN-LAST:event_botonMActionPerformed

    private void botonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNActionPerformed
        botonN.setVisible(false);
        palabraControlador.verificarLetra("N");// TODO add your handling code here:
    }//GEN-LAST:event_botonNActionPerformed

    private void botonOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOActionPerformed
       botonO.setVisible(false);
       palabraControlador.verificarLetra("O");
    }//GEN-LAST:event_botonOActionPerformed

    private void botonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPActionPerformed
      botonP.setVisible(false);
      palabraControlador.verificarLetra("P");// TODO add your handling code here:
    }//GEN-LAST:event_botonPActionPerformed

    private void botonQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQActionPerformed
      botonQ.setVisible(false);
      palabraControlador.verificarLetra("Q");// TODO add your handling code here:
    }//GEN-LAST:event_botonQActionPerformed

    private void botonTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTActionPerformed
       botonT.setVisible(false);
       palabraControlador.verificarLetra("T");// TODO add your handling code here:
    }//GEN-LAST:event_botonTActionPerformed

    private void botonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRActionPerformed
       botonR.setVisible(false);
       palabraControlador.verificarLetra("R");// TODO add your handling code here:
    }//GEN-LAST:event_botonRActionPerformed

    private void botonSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSActionPerformed
       botonS.setVisible(false);
       palabraControlador.verificarLetra("S");// TODO add your handling code here:
    }//GEN-LAST:event_botonSActionPerformed

    private void botonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUActionPerformed
       botonU.setVisible(false);
       palabraControlador.verificarLetra("U");// TODO add your handling code here:
    }//GEN-LAST:event_botonUActionPerformed

    private void botonVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVActionPerformed
      botonV.setVisible(false);
      palabraControlador.verificarLetra("V");// TODO add your handling code here:
    }//GEN-LAST:event_botonVActionPerformed

    private void botonWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonWActionPerformed
       botonW.setVisible(false);
       palabraControlador.verificarLetra("W");// TODO add your handling code here:
    }//GEN-LAST:event_botonWActionPerformed

    private void botonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonZActionPerformed
       botonZ.setVisible(false);
       palabraControlador.verificarLetra("Z");// TODO add your handling code here:
    }//GEN-LAST:event_botonZActionPerformed

    private void botonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonXActionPerformed
       botonX.setVisible(false);
       palabraControlador.verificarLetra("X");// TODO add your handling code here:
    }//GEN-LAST:event_botonXActionPerformed

    private void botonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonYActionPerformed
       botonY.setVisible(false);
       palabraControlador.verificarLetra("Y");// TODO add your handling code here:
    }//GEN-LAST:event_botonYActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        suma();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        resta();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel8PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabel8PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8PropertyChange

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
       System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReiniciarActionPerformed
       inicioJuego(); // TODO add your handling code here:
    }//GEN-LAST:event_jBtnReiniciarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jperdiste;
    private javax.swing.JButton botonA;
    private javax.swing.JButton botonB;
    private javax.swing.JButton botonC;
    private javax.swing.JButton botonD;
    private javax.swing.JButton botonE;
    private javax.swing.JButton botonF;
    private javax.swing.JButton botonG;
    private javax.swing.JButton botonH;
    private javax.swing.JButton botonI;
    private javax.swing.JButton botonJ;
    private javax.swing.JButton botonK;
    private javax.swing.JButton botonL;
    private javax.swing.JButton botonM;
    private javax.swing.JButton botonN;
    private javax.swing.JButton botonO;
    private javax.swing.JButton botonP;
    private javax.swing.JButton botonQ;
    private javax.swing.JButton botonR;
    private javax.swing.JButton botonS;
    private javax.swing.JButton botonT;
    private javax.swing.JButton botonU;
    private javax.swing.JButton botonV;
    private javax.swing.JButton botonW;
    private javax.swing.JButton botonX;
    private javax.swing.JButton botonY;
    private javax.swing.JButton botonZ;
    private javax.swing.JButton botonÑ;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JButton jBtnReiniciar;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabLetrasBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JLabel jPalabra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
