/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase27;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
/**
 *
 * @author Kyoz
 */
public class Cine extends javax.swing.JFrame {

    private final Complejo listita;
    private IComplejo Salta;

    /**
     * Creates new form Cine
     */
    public Cine() {
    this.listita = new Complejo();
    initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    
    public Cine(IComplejo Salta) {
        this.Salta = Salta; 
        listita =null;
        }

   
    
  
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1Salir = new javax.swing.JButton();
        jLabel1Titulo = new javax.swing.JLabel();
        jComboBox1Salas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1Butacas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1Reservar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2ButacasReservadas = new javax.swing.JList<>();
        jTextField1Pelicula = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1Salir.setText("Salir");
        jButton1Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, -1));

        jLabel1Titulo.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel1Titulo.setText("CINE HOYTS SALTA");
        getContentPane().add(jLabel1Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 260, 40));

        jComboBox1Salas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sala 1", "Sala 2", "Sala 3" }));
        jComboBox1Salas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1SalasItemStateChanged(evt);
            }
        });
        jComboBox1Salas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1SalasActionPerformed(evt);
            }
        });
        jComboBox1Salas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1SalasPropertyChange(evt);
            }
        });
        getContentPane().add(jComboBox1Salas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 90, 20));

        jList1Butacas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ButacasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1Butacas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 80, 220));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Peliculas por sala");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 150, 20));

        jButton1Reservar.setText("Reservar");
        getContentPane().add(jButton1Reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jScrollPane2.setViewportView(jList2ButacasReservadas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 80, 220));

        jTextField1Pelicula.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextField1PeliculaComponentAdded(evt);
            }
        });
        jTextField1Pelicula.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField1PeliculaCaretUpdate(evt);
            }
        });
        jTextField1Pelicula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1PeliculaMouseClicked(evt);
            }
        });
        jTextField1Pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1PeliculaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1Pelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 500, -1));

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jLabel1Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clase27/fondoAzul.jpg"))); // NOI18N
        jLabel1Fondo.setText("jLabel1");
        getContentPane().add(jLabel1Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 602, 445));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalirActionPerformed
      System.exit(0);
    }//GEN-LAST:event_jButton1SalirActionPerformed

    private void jComboBox1SalasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1SalasPropertyChange
   
         
    }//GEN-LAST:event_jComboBox1SalasPropertyChange

    private void jList1ButacasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ButacasValueChanged
    
      
    }//GEN-LAST:event_jList1ButacasValueChanged

    private void jComboBox1SalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1SalasActionPerformed
      
    }//GEN-LAST:event_jComboBox1SalasActionPerformed

    private void jTextField1PeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1PeliculaActionPerformed
       
       
    }//GEN-LAST:event_jTextField1PeliculaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1SalasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1SalasItemStateChanged
       
       
    }//GEN-LAST:event_jComboBox1SalasItemStateChanged

    private void jTextField1PeliculaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField1PeliculaCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1PeliculaCaretUpdate

    private void jTextField1PeliculaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextField1PeliculaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1PeliculaComponentAdded

    private void jTextField1PeliculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1PeliculaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1PeliculaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1Reservar;
    private javax.swing.JButton jButton1Salir;
    private javax.swing.JComboBox<String> jComboBox1Salas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Fondo;
    private javax.swing.JLabel jLabel1Titulo;
    private javax.swing.JList<String> jList1Butacas;
    private javax.swing.JList<String> jList2ButacasReservadas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1Pelicula;
    // End of variables declaration//GEN-END:variables
}
